project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - assignment04-Lab01-othmane.qmd
    - assignment04-Lab02-othmane.qmd
    - assignment04-Lab03-othmane.qmd
  

website:
  title: "Othmane Elouardi Portfolio"
  navbar:
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Assignment 04"
        menu:
          - text: "Lab 01 — Visual Reporting"
            href: assignment04-Lab01-othmane.qmd
          - text: "Lab 02 — Insights & Visualizations"
            href: assignment04-Lab02-othmane.qmd
          - text: "Lab 03 — Regression Modeling on Employment Data"
            href: assignment04-Lab03-othmane.qmd   



format:
  html:
    theme:
      light: lux
      dark: slate
    toc: true
    toc-location: right
    smooth-scroll: true
    code-fold: true
    code-tools: true
    code-line-numbers: true
    highlight-style: a11y
    css: styles.css
